### ISSUE TITLE
Missing EC2 ebs device size

### ISSUE THREAD

**Issue by EnSec4Git** [trussworks/terraform-aws-ecs-cluster#193]
When trying to create an ECS cluster using this module and the latest ECS-optimized AMI (currently `ami-037d203e54a0a9c14`), the Auto Scaling group, created by the module fails to reach capacity due to missing EBS volume size, resulting in this relatively opaque error:

` Error: "test": Waiting up to 10m0s: Need at least 1 healthy instances in ASG, have 0.`
...

` Description: "Launching a new EC2 instance.  Status Reason: The request must contain the parameter size or snapshotId. Launching EC2 instance failed."`

Versions: TF 1.0.6, terraform-aws-ecs-cluster 3.1.0
Tested with TF 0.12 and TAEC 2.0 as well (same result)

Steps to reproduce:
Follow the README and on Usage, replace `"amzn-ami-*-amazon-ecs-optimized"` with `"amzn2-ami-ecs-hvm-*-x86_64-ebs"`.

Expected: An ECS cluster is created
Actual result: An error is thrown, the AutoScaling Group is created, but not populated.

**Comment by rpdelaney** [comment]
@EnSec4Git If you are still facing this problem, please comment with your Terraform code in a code block and we'll take a look.
