### ISSUE TITLE
Allow additional security groups to be assigned to this resource

### ISSUE THREAD

**Issue by altinukshini** [trussworks/terraform-aws-ecs-cluster#30]
https://github.com/trussworks/terraform-aws-ecs-cluster/blob/d2b5cdc5c4dd5db8fbbca46c5647d08689925c85/main.tf#L133

Throwing a suggestion here, I think it would be very nice to allow other security groups to be assigned to this resource which can be passed through variables to the module...

**Comment by eeeady** [comment]
Thanks @altinukshini ! I put this work in our backlog and will get to it in the next couple weeks.

**Comment by ralren** [comment]
Taken care of in PR #37.
