### ISSUE TITLE
Feature: Use ECS Capacity Provider with ASG

### ISSUE THREAD

**Issue by aarushahuja-epi** [trussworks/terraform-aws-ecs-cluster#61]
ECS CAS can do managed scaling based on the cluster capacity on the ASG, use [Terraform's](https://www.terraform.io/docs/providers/aws/r/ecs_capacity_provider.html) `aws_ecs_capacity_provider" resource, attach the ASG to the capacity provider and the capacity provider to the cluster.

**Comment by brainsik** [comment]
Hi @aarushahuja-epi, thanks for the feature suggestion.

Pretty quickly after Fargate became widely available we stopped using EC2 backed clusters in favor of Fargate backed ones. Unless we end up doing some work for a client with a _very_ strong requirement for using EC2 backed clusters, it's unlikely we'd add this feature ourselves.

That said, if you submit a PR, we'd definitely consider merging it!
